# Generated by Django 3.2.9 on 2022-02-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_scopes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relationship',
            new_name='Scopes',
        ),
    ]
