# Generated by Django 3.2.9 on 2022-02-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_relationship_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopes',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='scopes',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='articles.scope', verbose_name='Раздел'),
        ),
    ]
