# Generated by Django 3.2.9 on 2021-12-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Название'),
        ),
    ]
